name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ssh-key
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run : |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
          echo "${ACTIONS_DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy
        env:
          PUBLISH_REPOSITORY: aenniw/ctf-stash
          PUBLISH_BRANCH: gh-pages
        run: |
          git remote add public git@github.com:${PUBLISH_REPOSITORY}.git
          git checkout -B ${PUBLISH_BRANCH}
          git push -f public ${PUBLISH_BRANCH}
